### ISSUE TITLE
update x-project-id values in .toc files

### ISSUE THREAD

**Issue by torkus** [SFX-WoW/Masque_Dominos#24]
hi there

I noticed your forks have retained the original project IDs. To avoid confusion would you consider updating or removing them?

These are what I found:

- [ ] `SFX-WoW/Masque_Dominos` shares `x-curse-project-id: 699643` with `tullamods/Dominos`
- [ ] `SFX-WoW/Masque_Dominos` shares `x-wowi-id: 26455` with `tullamods/Dominos`
- [ ] `SFX-WoW/Masque_Dominos` shares `x-wago-id: WL6JYRNv` with `tullamods/Dominos`
- [ ] `SFX-WoW/Masque` shares `x-curse-project-id: 13592` with `RealUI/RealUI`
- [ ] `SFX-WoW/Masque` shares `x-wowi-id: 12097` with `RealUI/RealUI`
- [ ] `SFX-WoW/Masque` shares `x-wago-id: kRNLgpGo` with `RealUI/RealUI`

Cheers,

**Comment by StormFX** [comment]
Those are the correct IDs for my projects. Otherwise, they would not be able to be published since I use the BigWigsPackager to push them to those web sites and it uses those IDs.

**Comment by torkus** [comment]
You're right, I'm mistaken. Some bad data has crept in to my catalogue.

Thanks for your patience.

**Comment by StormFX** [comment]
ss
